### ISSUE TITLE
[Feature Request] Render Muliti Doc Smultaneously

### ISSUE THREAD

**Issue by ToddRuan0** [funbox/blueprinter#18]
I have a folder just like:
folder/
---- a.apib
---- b.apib
---- c.apib

Can I just use `blueprinter -i folder/*.apib -s -p 3000` to render all doc in the folder?

**Comment by Ge11ert** [comment]
Hi @ToddRuan0! Thanks for your interest in our tools, but at first we need to clarify some things.

You've written about rendering multiple docs from a folder, but from your message it is not clear what is the result you expect to see? Do you want to run multiple servers on different ports or do you want to somehow glue the files together and render on a single port and have some kind of navigation? So many questions, so few answers =)

Another problem is the `*.apib` notation. You see, an APIB-file has single entry point. You can split your documentation into separate blocks and include them into your index file. If you want to render *all files* in a folder, you can encounter an error when a file is considered as an entry point but it is just a separated block of another APIB-doc.

For now, it seems that your problem can be solved by writing a custom bash-script that will somehow obtain a list of index files and then use each filename from that list as an entry point in `-input <file>` argument.

**Comment by ToddRuan0** [comment]
@Ge11ert 
Thanks for the reply!

Now I know the best solution for me is to render all doc to HTML in a folder
and use tool like Gulp to watch the file and create a local server to show the HTML.

It work for me.

Thanks for your help.
