### ISSUE TITLE
Custom Favicon

### ISSUE THREAD

**Issue by duckchip** [funbox/blueprinter#25]
Hey guys,

Awesome repo!

Question: Would it be possible to include a flag to provide a custom favicon? :) Or is there another way to use a custom one? 

Thanks!

**Comment by Steerlin** [comment]
👍 yes please, good idea !

**Comment by Ge11ert** [comment]
At this time, there is no option to use a custom favicon. But I'm going to have a look at this possible feature and come back with either an implementation or an answer

**Comment by Ge11ert** [comment]
@Steerlin @duckchip this feature has landed in version 5.4.0. Please, be aware that a custom favicon can be applied only in build mode. See [readme](https://github.com/funbox/blueprinter/blob/master/README.md?plain=1#L76)
