### ISSUE TITLE
Markdown in attribute description

### ISSUE THREAD

**Issue by igoradamenko** [funbox/blueprinter#4]
Hey there!

We use Blueprinter for our project's API docs and today we've tried to add the response attributes like this:

```apib
+ Response 200 (application/json)
    + Attributes
        + status: `insufficientFunds` (string, required, fixed) - CP вернул [5051](https://developers.cloudpayments.ru/#kody-oshibok)
```

But suddenly Blueprinter has rendered such APIB without processing the Markdown:

![image](https://user-images.githubusercontent.com/6537798/180885909-3d640b1f-dd77-48fa-804f-0f1dbb997204.png)

Have we done something wrong? Is it possible to enable Markdown parsing, or add such feature in the future?

We're using `@funboxteam/blueprinter@5.0.1`.

**Comment by Ge11ert** [comment]
> Have we done something wrong?

~Empire~ you did nothing wrong. According to my memory and git history, we always just display a description as plain text without some transformation. So this is may be a feature to implement.

**Comment by igoradamenko** [comment]
Yaay! It works, thanks!

![image](https://user-images.githubusercontent.com/6537798/181271938-aed0a8ea-c038-4ef1-a653-8f03aeb00390.png)
