### ISSUE TITLE
Allow composition of apib files

### ISSUE THREAD

**Issue by MSchmidt** [funbox/blueprinter#40]
I don't think it was ever part of the official spec but aglio allowed to compose documentation out of several `.apib` files. I could do something like this:

```
# Group Files
:::note
All File requests require Admin Privileges.
:::
<!-- include(_files.apib) -->
```

This would place the content of `_files.apib` at this position. From my tests this directive is just ignored by `blueprinter`.

**Comment by goganchic** [comment]
Hello! Take a look at this example https://github.com/funbox/api-blueprint-tutorial/blob/master/examples/13-imports.apib. You can read more about this feature in the specification https://github.com/funbox/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-import.

**Comment by MSchmidt** [comment]
Thank you! Sorry I didn't find this myself.

**Comment by MSchmidt** [comment]
I adjusted my docs but came across another issue. I did not just include more apib files but also other files. Like csutom example json. This does not work with the Import directive. So I guess it's definitively not officially supported but still worked in aglio. Any other idea how I could just include arbitrary content?
