### ISSUE TITLE
Table Support

### ISSUE THREAD

**Issue by mmadson** [funbox/blueprinter#42]
Thank you for picking up where Aglio and others have left off. One feature request would be to add markdown table support, especially useful in the overview page. 

For example:

```md
Header1 | Header2 | Header3
--:| ---- | -----------
Cell Val 1 | Cell Val 2 | Cell Val 3
```

**Comment by Ge11ert** [comment]
Yes, tables... You see, we use pure Commonmark to parse markdown in APIB files and such table syntax as in your example is not a part of the core commonmark specification.
Actually, these tables are available as an extension to GFM (github flavored markdown): https://github.github.com/gfm/#tables-extension-

If you google something like "commonmark tables", you'll find a lot of topics with questions like "when tables will be part of core commonmark spec?". 

I assume there are no plans to switch markdown parser completely in Blueprinter and/or Crafter.

For now, you can use HTML to insert your tables into APIB files:

Such code in raw content (description) section
```
An example of an image:
<img src="https://via.placeholder.com/200/1EBC86/14182F" alt="Wow! This is image." width="200"/>

An example of a table:
<table>
  <thead>
    <tr>
      <th>Header</th>
      <th>Another Header</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>field 1</td>
      <td>value one</td>
    </tr>
  </tbody>
</table>
```
will be rendered as
![image](https://github.com/funbox/blueprinter/assets/22282247/44b868cd-3417-4c92-a335-783275e6833b)

**Comment by mmadson** [comment]
This is a perfect work around, thank you very much.
